# The loopback interface.
[[net.interfaces]]
index = 1

# The ethernet interface.
[[net.interfaces]]
index = 2
addr = "192.168.1.26"
gateway = "192.168.1.254"
broadcast = "255.255.255.0"

[ui]
user = "greg"

[ui.env]
EDITOR = "nvim"
PAGER = "less"
PASSWORD_STORE_DIR = "/bubble/passwd"
